PatientTrackerProject/Controllers/ClerkController.cs
using PatientTracker.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace PatientTracker.Controllers
{
   
    public class ClerkController : Controller
    {
        // GET: Clerk
        PatientTrackerContext trackerContext = new PatientTrackerContext();
        public ActionResult Index()
        {
            return View();
        }

       
        public ActionResult ClerkRegister()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ClerkRegister(ClerkDL clerkDL)
        {
            try
            {

                Random rd = new Random();
                if (ModelState.IsValid)
                {
                    clerkDL.ClerkId = "CL" + rd.Next(1001, 9999).ToString();
                    clerkDL.ClerkStatus = "Pending";
                    trackerContext.Clerks.Add(clerkDL);
                    trackerContext.SaveChanges();
                    ViewBag.MessageSucess = "You Details are Successfully Submitted With Clerk ID  :" + clerkDL.ClerkId;


                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Unable to Register");
                }
            }
            catch
            {
                string controllername = this.ControllerContext.RouteData.Values["controller"].ToString();
                string actionname = this.ControllerContext.RouteData.Values["action"].ToString();
                string message = "Exception occured in " + actionname + " in " + controllername;

                TempData["errorMessage"] = message;
                return RedirectToAction("ErrorInfo");
            }
            return View();
        }
        public ActionResult ErrorInfo()
        {
            ViewBag.Message = TempData["errorMessage"];
            return View();
        }

        public ActionResult ClerkLogin()
        {
            if (Session["ClerkId"] != null)
            {
                TempData.Keep();
                return RedirectToAction("ClerkHome");
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ClerkLogin(ClerkDL clerkDL)
        {
            try
            {
                if (clerkDL.ClerkId != null)
                {
                    var data = trackerContext.Clerks.Where(x => x.ClerkId == clerkDL.ClerkId && x.Password == clerkDL.Password).FirstOrDefault();
                    if (data != null && data.ClerkStatus == "Active")
                    {
                        Session["ClerkId"] = data.ClerkId.ToString();
                        TempData["User"] = data.FirstName;
                        TempData["UserId"] = data.ClerkId;
                        TempData.Keep();
                        return RedirectToAction("ClerkHome");
                    }
                    else
                    {
                        ViewBag.Message = "Please Register or Your Status is Pending Wait for Approve";
                    }
                }
                else
                {
                    ViewBag.MessageLO = "* Doctor Id Required";
                }
            }
            catch
            {
                string controllername = this.ControllerContext.RouteData.Values["controller"].ToString();
                string actionname = this.ControllerContext.RouteData.Values["action"].ToString();
                string message = "Exception occured in " + actionname + " in " + controllername;

                TempData["errorMessage"] = message;
                return RedirectToAction("ErrorInfo");
            }


            return View(clerkDL);
        }

        public ActionResult ClerkHome()
        {
            if (Session["clerkId"] != null)
            {
                ViewBag.Welcome = TempData["User"];
                TempData.Keep();
                return View();
            }
            else
            {
                return RedirectToAction("ClerkLogin");
            }
        }

        public ActionResult ClerkLogout()
        {
            Response.Cookies.Clear();
            Session.Abandon();
            return RedirectToAction("ClerkLogin");
        }
        public ActionResult ClerkSearch()
        {
            return View();
        }

        public ActionResult ClerkPatientHome()
        {
            if (Session["ClerkId"] != null)
            {
                var data = trackerContext.Patients.ToList();
                return View(data);
            }
            else
            {
                return RedirectToAction("ClerkLogin");
            }
            
        }

        public ActionResult EditClerkPatient(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var data = trackerContext.Patients.Find(id);
            if (data == null)
            {
                return HttpNotFound();
            }

            return View(data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditClerkPatient(PatientDL patientDL)
        {
            if (ModelState.IsValid)
            {
                trackerContext.Entry(patientDL).State = System.Data.Entity.EntityState.Modified;
                trackerContext.SaveChanges();
                ViewBag.MessageSuccess = "Updated Details Successfully";
                return RedirectToAction("ClerkPatientHome");
            }
            return View();
        }

        public ActionResult ClerkPatientDetails(string id)
        {
            var data = trackerContext.Patients.Find(id);
            if (data == null)
            {
                return HttpNotFound();
            }
            return View(data);
        }

        public ActionResult ClerkPatientDelete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PatientDL patientDL = trackerContext.Patients.Find(id);
            if (patientDL == null)
            {
                return HttpNotFound();
            }
            return View(patientDL);
        }
        [HttpPost, ActionName("ClerkPatientDelete")]
        public ActionResult DeleteConfirmed(string id)
        {
            if (ModelState.IsValid)
            {
                PatientDL patientDL = trackerContext.Patients.Find(id);
                trackerContext.Patients.Remove(patientDL);
                trackerContext.SaveChanges();
                return RedirectToAction("ClerkPatientHome");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Failed To Delete");
            }
            return View();
        }

        public ActionResult ClerkPatientTestDetails()
        {
            var data = trackerContext.medicalTests.ToList();
            return View(data);
        }

        public ActionResult EditClerkPatientTest(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var data = trackerContext.medicalTests.Find(id);
            if (data == null)
            {
                return HttpNotFound();
            }
            return View(data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditClerkPatientTest(MedicalTestDL medicalTest)
        {
            try
            {

                trackerContext.Entry(medicalTest).State = EntityState.Modified;
                trackerContext.SaveChanges();
                ViewBag.Message = "data updated successfully";
                return RedirectToAction("ClerkPatientTestDetails");
            }
            catch
            {
                string controllername = this.ControllerContext.RouteData.Values["controller"].ToString();
                string actionname = this.ControllerContext.RouteData.Values["action"].ToString();
                string message = "Exception occured in " + actionname + " in " + controllername;

                TempData["errorMessage"] = message;
                return RedirectToAction("ErrorInfo");
            }

        }

        public ActionResult PatientTestDetails(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var data = trackerContext.medicalTests.Find(id);
            if (data == null)
            {
                return HttpNotFound();
            }
            return View(data);
        }

        public ActionResult ClerkPatientTestDelete(string id)
        {
            if (Session["clerkId"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var data = trackerContext.medicalTests.Find(id);
                if (data == null)
                {
                    return HttpNotFound();
                }
                return View(data);
            }
            else
            {
                return RedirectToAction("AdminLogin");
            }
        }
        [HttpPost, ActionName("ClerkPatientTestDelete")]
        public ActionResult ClerkPatientTestDeleteConfirmed(string id)
        {
            try
            {
                MedicalTestDL medicalTest = trackerContext.medicalTests.Find(id);

PatientTrackerProject/Views/Clerk/ClerkHome.cshtml

@{
    ViewBag.Title = "ClerkHome";
}

<h2>Clerk Home</h2>

<style>
    #xyz{
        float:right;
    }
    body {
        background-color: lightskyblue;
    }
</style>
<div id="xyz">
    <b>Welcome @ViewBag.Welcome</b> |
    <b>@Html.ActionLink("account","ClerkDetails")</b> |
    <b>@Html.ActionLink("Logout", "ClerkLogout", "Clerk")</b>
</div>

<div>
    <table class="table table-striped">
        <tr>
            <td><b>@Html.ActionLink("Available Patients", "ClerkPatientHome")</b></td>
            <td><b>@Html.ActionLink("Patient Test Details", "ClerkPatientTestDetails")</b></td>
            @*<td><b>@Html.ActionLink("Patient Billing Details", "ClerkPatientBillingDetails")</b></td>*@
        </tr>
    </table>
</div>

PatientTrackerProject/Views/Clerk/ClerkLogin.cshtml
@model PatientTracker.Models.ClerkDL

@{
    ViewBag.Title = "ClerkLogin";
}

<style>
    body {
        background-color: lightskyblue;
    }

    #xyz {
        float: right;
    }
</style>

<h2>Clerk Login</h2>
<div id="xyz">
    <h4>@Html.ActionLink("New Clerk Registration", "ClerkRegister", "Clerk")</h4>
</div>
<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ClerkId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClerkId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClerkId, "", new { @class = "text-danger" })
                <p class="text-danger">@ViewBag.MessageLO</p>
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
                <b>@Html.ActionLink("Forgot Password", "ClerkSearch", "Clerk")</b>
            </div>
        </div>
    </div>
}
<div class="text-danger">
    <b>@ViewBag.Message</b>
</div>
<div>
    @Html.ActionLink("Back to List", "TrackingHome", "Home")
</div>

PatientTrackerProject/Views/Clerk/ClerkPatientDelete.cshtml
@model PatientTracker.Models.PatientDL

@{
    ViewBag.Title = "ClerkPatientDelete";
}
<style>
    body {
        background-color: lightskyblue;
    }
</style>
<h2>Clerk Patient Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.PatientId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PatientStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PatientSecuirtyQuestion1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientSecuirtyQuestion1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PatientSecurityAnswer1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientSecurityAnswer1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PatientSecuirtyQuestion2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientSecuirtyQuestion2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PatientSecurityAnswer2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientSecurityAnswer2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PatientSecuirtyQuestion3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientSecuirtyQuestion3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PatientSecurityAnswer3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientSecurityAnswer3)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "ClerkPatientHome")
        </div>
    }
</div>

PatientTrackerProject/Views/Clerk/ClerkPatientDetails.cshtml
@model PatientTracker.Models.PatientDL

@{
    ViewBag.Title = "ClerkPatientDetails";
}
<style>
    body {
        background-color: lightskyblue;
    }
</style>
<h2>Clerk Patient Details</h2>

<div>
    
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.PatientId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PatientStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PatientSecuirtyQuestion1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientSecuirtyQuestion1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PatientSecurityAnswer1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientSecurityAnswer1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PatientSecuirtyQuestion2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientSecuirtyQuestion2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PatientSecurityAnswer2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientSecurityAnswer2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PatientSecuirtyQuestion3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientSecuirtyQuestion3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PatientSecurityAnswer3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientSecurityAnswer3)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "EditClerkPatient", new { id = Model.PatientId }) |
    @Html.ActionLink("Back to List", "ClerkPatientHome")
</p>

PatientTrackerProject/Views/Clerk/ClerkPatientHome.cshtml
@model IEnumerable<PatientTracker.Models.PatientDL>

@{
    ViewBag.Title = "ClerkPatientHome";
}
<style>
    body {
        background-color: lightskyblue;
    }
</style>
<h2>Clerk Patient Home</h2>
<p>
    @Html.ActionLink("Add Patient","PatientRegister","Patient")
</p>

<table class="table table-bordered table-responsive table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PatientId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContactNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PatientStatus)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.PatientId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.FirstName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.LastName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Age)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Gender)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ContactNumber)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.PatientStatus)
    </td>
    <td>
        @Html.ActionLink("Edit", "EditClerkPatient", new { id = item.PatientId }) |
        @Html.ActionLink("Details", "ClerkPatientDetails", new { id = item.PatientId }) |
        @Html.ActionLink("Delete", "ClerkPatientDelete", new { id = item.PatientId })
    </td>
</tr>
}

</table>

<div>
    <b>@Html.ActionLink("Go Back","ClerkHome")</b>
</div>

PatientTrackerProject/Views/Clerk/ClerkPatientTestDelete.cshtml
@model PatientTracker.Models.MedicalTestDL

@{
    ViewBag.Title = "ClerkPatientTestDelete";
}
<style>
    body {
        background-color: lightskyblue;
    }
</style>
<h2>Clerk Patient Test Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MedicalTestDL</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TestId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TestId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DoctorId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoctorId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.doctors.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.doctors.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PatientId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.patients.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.patients.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TestType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TestType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DoctorType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoctorType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfTestAppointment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfTestAppointment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TestRequest)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TestRequest)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TestCompletedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TestCompletedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TestResult)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TestResult)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TestStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TestStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TestDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TestDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Treatment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Treatment)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "ClerkPatientTestDetails")
        </div>
    }
</div>

PatientTrackerProject/Views/Clerk/ClerkPatientTestDetails.cshtml
@model IEnumerable<PatientTracker.Models.MedicalTestDL>

@{
    ViewBag.Title = "ClerkPatientTestDetails";
}
<style>
    body {
        background-color: lightskyblue;
    }
</style>
<h2>Clerk Patient Test Details</h2>


<table class="table table-bordered table-responsive table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TestId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.doctors.DoctorId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.doctors.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.patients.PatientId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.patients.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TestType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DoctorType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfTestAppointment)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TestStatus)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.TestId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.doctors.DoctorId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.doctors.FirstName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.patients.PatientId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.patients.FirstName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.TestType)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DoctorType)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DateOfTestAppointment)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.TestStatus)
    </td>

    <td>
        @Html.ActionLink("Edit", "EditClerkPatientTest", new { id = item.TestId }) |
        @Html.ActionLink("Details", "PatientTestDetails", new { id = item.TestId }) |
        @Html.ActionLink("Delete", "ClerkPatientTestDelete", new { id = item.TestId }) |
        @Html.ActionLink("Create Bill", "TestPrescriptionDetails", new { id = item.TestId })
    </td>
</tr>
}

</table>

<div>
    <b>@Html.ActionLink("Back to List", "ClerkHome")</b>
</div>

PatientTrackerProject/Views/Clerk/PatientTestDetails.cshtml
@model PatientTracker.Models.MedicalTestDL

@{
    ViewBag.Title = "PatientTestDetails";
}
<style>
    body {
        background-color: lightskyblue;
    }
</style>
<h2>Patient Test Details</h2>

<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TestId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TestId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.doctors.DoctorId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.doctors.DoctorId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.doctors.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.doctors.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.patients.PatientId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.patients.PatientId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.patients.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.patients.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TestType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TestType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DoctorType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DoctorType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfTestAppointment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfTestAppointment)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TestRequest)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TestRequest)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TestCompletedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TestCompletedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TestResult)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TestResult)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TestStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TestStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TestDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TestDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Treatment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Treatment)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "EditClerkPatientTest", new { id = Model.TestId }) |
    @Html.ActionLink("Back to List", "ClerkPatientTestDetails")
</p>